version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
  neo4j:
    image: neo4j:4.4.0
    restart: always
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - ./neo4j/test/data:/data
      - ./neo4j/test/logs:/logs
      - ./neo4j/test/import:/var/lib/neo4j/import
      - ./neo4j/test/plugins:/plugins
      - ./neo4j/seed-data:/var/lib/neo4j/import/seed-data
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4JLABS_PLUGINS=\[\"apoc\"\]
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
